import { colors } from '@/styles/colors';
import breakpoints from '@/styles/breakpoints';

export default {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: '2rem',
    background: colors.gradients.gradient1,
    width: '100%',
    padding: '2rem',
    borderRadius: '1.5rem',
    [`@media (min-width:${breakpoints.values.lg}px)`]: {
      minWidth: '800px',
    },
  },
  accordion: {
    width: '100%',
    backgroundColor: 'transparent',
    boxShadow: 'none',
    color: colors.background.default,
    '&:before': { display: 'none' },
  },
  accordionSummary: {
    color: colors.background.default,
  },
  tasksHeading: {
    fontSize: '3rem',
    fontWeight: 700,
    color: colors.background.card,
    padding: '0.25rem',
  },
  toolbar: {
    display: 'flex',
    flexDirection: 'row',
    position: 'sticky',
    justifyContent: 'flex-end',
    zIndex: 50,
    top: '5rem',
    gap: '1rem',
    margin: '0.5rem',
    marginLeft: 'auto',
    backgroundColor: colors.background.muted,
    padding: '0.5rem',
    borderRadius: '0.75rem',
    width: 'fit-content',
  },
  taskSection: {
    width: '100%',
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
    padding: '1.25rem',
    backgroundColor: colors.background.card,
    borderRadius: '1.5rem',
    marginBottom: '1.25rem',
  },
  taskSectionEditing: {
    border: `4px solid ${colors.destructive.main}`,
  },
  taskHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    backgroundColor: colors.background.default,
    padding: '1.25rem',
    borderRadius: '0.75rem',
    color: colors.primary.main,
  },
  taskTypeText: {
    fontWeight: 600,
    color: colors.text.primary,
  },
  taskMeta: {
    color: colors.text.muted,
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  questionRow: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '0.5rem',
    width: '100%',
  },
  questionInput: {
    backgroundColor: colors.background.card,
    borderRadius: '0.75rem',
    '& .MuiInputBase-input': {
      fontWeight: 600,
      color: colors.text.cardForeground,
    },
  },
  questionText: {
    fontWeight: 600,
    color: colors.text.cardForeground,
    padding: '0.5rem',
    backgroundColor: colors.background.card,
    borderRadius: '0.75rem',
  },
  imageWrap: {
    position: 'relative',
    width: '800px',
    height: '600px',
  },
  image: {
    borderRadius: '0.5rem',
    alignSelf: 'center',
    backgroundColor: colors.background.default,
    padding: '0.25rem',
    objectFit: 'contain',
  },
  noImageBox: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.background.default,
    padding: '0.25rem',
    color: colors.text.primary,
  },
  answersWrap: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: colors.background.default,
    borderRadius: '0.375rem',
    color: colors.primary.main,
  },
  answersHeaderRow: {
    display: 'flex',
    flexDirection: 'row',
    margin: '0.5rem',
    justifyContent: 'space-between',
  },
  answersHeaderLabel: {
    fontWeight: 600,
    color: colors.text.primary,
  },
  answerRow: {
    display: 'flex',
    gap: '0.5rem',
    margin: '0.25rem',
    backgroundColor: colors.background.default,
    justifyContent: 'space-between',
    padding: '0.75rem',
    borderRadius: '0.375rem',
    color: colors.text.primary,
    borderBottom: `2px solid ${colors.border.default}`,
    '&:last-of-type': { borderBottom: 'none' },
    alignItems: 'center',
  },
  answerInput: {
    maxWidth: '42rem',
    backgroundColor: colors.background.card,
    borderRadius: '0.75rem',
  },
  answerText: {
    maxWidth: '42rem',
    color: colors.text.primary,
  },
  emptyHeading: {
    fontSize: '3rem',
    fontWeight: 700,
    color: colors.background.card,
    padding: '0.25rem',
  },
};
